# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#to manually trigger from gcloud
# gcloud builds submit --config=deploy.yaml --project=project-name --region=us-west1
# [START Cloudbuild_config]
steps:
  #Docker Build
- id: 'Apply Integration scaffolding configuration'
  name: us-docker.pkg.dev/appintegration-toolkit/images/integrationcli:latest
  args:
    - integrations
    - apply
    - -f
    - .
    - --wait=${_WAIT}
    - --reg=us-east1
    - --proj=${_PROJECT_ID}    
    - --token=ya29.a0AfB_byCd7f6glqL8NanWN0x3Xw4OJ5oZ_9cr9dZ7J3dgXNJ-Ti01g-8K3NncqnAf8vq3OOgiL6lDjlZvvKwIPCIcw_tYoVwwR3o3cKfLkI-PTJYGcR9V2reWlhmlv5BIshW6FAN1ScQ2HOLxnZ0QCHja3irXxmkjjDk771yOohCJaCgYKAb4SARESFQHGX2MipcxCWcgFTjMQxr3mVUYtkQ0179
    #- --sa=${_SERVICE_ACCOUNT_NAME}
    - $(cat /tmp/cmd)
    # uncomment these as necessary
    #- --g=${_GRANT_PERMISSIONS}
    #- --create-secret=${_CREATE_SECRET}
    #- -k=locations/$LOCATION/keyRings/${_KMS_RING_NAME}/cryptoKeys/${_KMS_KEY_NAME}
    #- --sa=${_SERVICE_ACCOUNT_NAME}

#the name of the service account  to use when setting up the connecto
substitutions:
  _GRANT_PERMISSIONS: "true"
  _CREATE_SECRET: "false"
  _ENCRYPTED: "false"
  _DEFAULT_SA: "false"
  _SERVICE_ACCOUNT_NAME: "connectors"
  _KMS_RING_NAME: "app-integration"
  _KMS_KEY_NAME: "integration"
  _WAIT: "false"

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: "ALLOW_LOOSE"